[project]
name = "ext data"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [

]





[tool.flet]
org = "com.extdata"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "ext data"

# company name to display in about app dialogs
company = "ext data"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2025 by Flet"






[tool.uv]
dev-dependencies = [
    "flet[all]==0.26.0",
    
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
flet = {extras = ["all"], version = "0.26.0"}